#!/usr/bin/env bash
# trend-hunt.sh
# Fetches trending topics from Reddit, GitHub, and Hacker News
# and writes a markdown report for the Product Forge agents to analyze.
#
# Usage:
#   ./trend-hunt.sh [output-file]
#   Output defaults to ~/reports/trends-YYYYMMDD-HHMMSS.md

set -euo pipefail

REPORTS_DIR="${HOME}/reports/trends"
mkdir -p "${REPORTS_DIR}"

OUTPUT_FILE="${1:-${REPORTS_DIR}/trends-$(date +%Y%m%d-%H%M%S).md}"
UA="OpenClaw-ProductForge/1.0 (trend-hunt; contact=productforge-bot)"

log() { echo "  $*" >&2; }

# ── Header ────────────────────────────────────────────────────────────────────

cat > "${OUTPUT_FILE}" <<HEADER
# Trend Report — $(date -u '+%Y-%m-%d %H:%M UTC')

This report was automatically generated by \`trend-hunt.sh\`.
Feed it to the Product Strategist and Researcher for analysis.

---
HEADER

# ── Reddit ────────────────────────────────────────────────────────────────────

echo "" >> "${OUTPUT_FILE}"
echo "## Reddit — Top Posts This Week" >> "${OUTPUT_FILE}"

SUBREDDITS=(
  "startups"
  "SideProject"
  "entrepreneur"
  "programming"
  "webdev"
  "MachineLearning"
  "artificial"
  "hacking"
  "netsec"
)

for sub in "${SUBREDDITS[@]}"; do
  log "Fetching r/$sub..."
  echo "" >> "${OUTPUT_FILE}"
  echo "### r/${sub}" >> "${OUTPUT_FILE}"

  response=$(curl -sf \
    -H "User-Agent: ${UA}" \
    "https://www.reddit.com/r/${sub}/top.json?t=week&limit=8" \
    2>/dev/null) || { echo "_[fetch failed]_" >> "${OUTPUT_FILE}"; sleep 2; continue; }

  echo "${response}" \
    | jq -r '.data.children[]
        | select(.data.score > 10)
        | "- **\(.data.title)** (↑\(.data.score) | \(.data.num_comments) comments)\n  <https://reddit.com\(.data.permalink)>"' \
    2>/dev/null >> "${OUTPUT_FILE}" \
    || echo "_[parse failed]_" >> "${OUTPUT_FILE}"

  sleep 1  # be kind to Reddit's rate limits
done

# ── Hacker News ───────────────────────────────────────────────────────────────

echo "" >> "${OUTPUT_FILE}"
echo "## Hacker News — Ask HN & Show HN (Recent)" >> "${OUTPUT_FILE}"

log "Fetching HN Ask/Show posts..."

for tag in "ask_hn" "show_hn"; do
  label=$(echo "${tag}" | tr '_' ' ' | tr '[:lower:]' '[:upper:]')
  echo "" >> "${OUTPUT_FILE}"
  echo "### ${label}" >> "${OUTPUT_FILE}"

  hn_response=$(curl -sf \
    "https://hn.algolia.com/api/v1/search?tags=${tag}&hitsPerPage=8" \
    2>/dev/null) || { echo "_[fetch failed]_" >> "${OUTPUT_FILE}"; continue; }

  echo "${hn_response}" \
    | jq -r '.hits[]
        | "- **\(.title)** (↑\(.points) | \(.num_comments) comments)\n  <https://news.ycombinator.com/item?id=\(.objectID)>"' \
    2>/dev/null >> "${OUTPUT_FILE}" \
    || echo "_[parse failed]_" >> "${OUTPUT_FILE}"
done

# ── GitHub Trending (via Search API) ─────────────────────────────────────────

echo "" >> "${OUTPUT_FILE}"
echo "## GitHub — Trending This Week" >> "${OUTPUT_FILE}"
log "Fetching GitHub trending..."

SINCE_DATE=$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null \
  || date -v-7d +%Y-%m-%d 2>/dev/null \
  || echo "2024-01-01")

for topic in "" "ai" "developer-tools" "automation"; do
  if [[ -n "${topic}" ]]; then
    query="topic:${topic}+created:>${SINCE_DATE}"
    label="Topic: ${topic}"
  else
    query="stars:>50+created:>${SINCE_DATE}"
    label="All Languages"
  fi

  echo "" >> "${OUTPUT_FILE}"
  echo "### GitHub Trending — ${label}" >> "${OUTPUT_FILE}"

  gh_response=$(curl -sf \
    -H "Accept: application/vnd.github+json" \
    -H "User-Agent: ${UA}" \
    "https://api.github.com/search/repositories?q=${query}&sort=stars&order=desc&per_page=8" \
    2>/dev/null) || { echo "_[fetch failed — may need GITHUB_TOKEN env var]_" >> "${OUTPUT_FILE}"; continue; }

  echo "${gh_response}" \
    | jq -r '.items[]
        | "- **[\(.full_name)](\(.html_url))** ⭐\(.stargazers_count)\n  \(.description // "_No description_")\n  Language: \(.language // "N/A") | Topics: \((.topics // []) | join(", "))"' \
    2>/dev/null >> "${OUTPUT_FILE}" \
    || echo "_[parse failed]_" >> "${OUTPUT_FILE}"

  sleep 1
done

# ── Product Hunt (public RSS) ─────────────────────────────────────────────────

echo "" >> "${OUTPUT_FILE}"
echo "## Product Hunt — Recent Launches" >> "${OUTPUT_FILE}"
log "Fetching Product Hunt..."

ph_response=$(curl -sf \
  -H "User-Agent: ${UA}" \
  "https://www.producthunt.com/feed" \
  2>/dev/null) || ph_response=""

if [[ -n "${ph_response}" ]]; then
  echo "${ph_response}" \
    | grep -oP '(?<=<title>)[^<]+' \
    | grep -v "^Product Hunt" \
    | head -10 \
    | while read -r title; do echo "- ${title}"; done \
    >> "${OUTPUT_FILE}" 2>/dev/null \
    || echo "_[parse failed]_" >> "${OUTPUT_FILE}"
else
  echo "_[fetch failed]_" >> "${OUTPUT_FILE}"
fi

# ── Footer ────────────────────────────────────────────────────────────────────

cat >> "${OUTPUT_FILE}" <<FOOTER

---

## Agent Instructions

**Product Strategist:** Review this report. Score the top 3 opportunities using the brief template. Write briefs to \`~/ideas/briefs/\`.

**Researcher:** For the top-scoring opportunities from the Strategist, run competitive research and feasibility checks. Write findings to \`~/reports/research/\`.

**Designer + Implementer + Tester:** Await briefs and specs before beginning.

---
_Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_
_Next run: in ~4 hours (see openclaw cron)_
FOOTER

log "Done. Report written to: ${OUTPUT_FILE}"
echo "${OUTPUT_FILE}"
